project:
  type: book
  output-dir: docs
  
execute:
  freeze: auto

lang: pt 
language:
  title-block-author-single: "Autor"

book:
  title: "Análise de dados criminais usando linguagem R"
  site-url: "https://arturdamiao.github.io/2026-02-summer-intro-crime-analysis-R/"
  repo-url: "https://github.com/arturdamiao/2026-02-summer-intro-crime-analysis-R"
  navbar:
    logo: logo_en.png
    right: 
      - text: "Materiais"
        menu:
          - text: "Introdução à Programação para Humanidades"
            href: "https://youtube.com/playlist?list=PLInYN7O8R1DRcWN5pRvZfrG65RgtP1OB1&si=_Izok__wwjtfNpVH"
          - text: "Análise de dados criminais usando linguagem R"
            href: "https://github.com/arturdamiao/2026-02-summer-intro-crime-analysis-R"

  chapters:
    - part: "Pré-curso"
      chapters:
        - index.qmd
        - instalacao.qmd
    - part: "Como analisar dados criminais?"
      chapters:
        - 01-introducao.qmd


  # - part: "Pré-curso"
  #   chapters:
  #     - text: "Página inicial"
  #       href: index.qmd  
  #     - href: instalacao.qmd


page-navigation: true

page-footer: 
  border: true
  left: "Copyright 2026, Artur Damião" 
  right: 
    - icon: github
      href: https://github.com/arturdamiao/2026-02-summer-intro-crime-analysis-R


format:
  html:
    theme: cosmo
#    css: styles.css
    toc: true
    toc-depth: 5
    link-external-icon: false
    link-external-newwindow: true
    reference-location: margin

bibliography: references.bib

editor: source
code-annotations: hover

author:
  - name: "Artur Damião"
    url: "https://www.arturdamiao.com/"
    email: "arturcardoso@usp.br"
    orcid: 0000-0002-8628-1653
    affiliation: 
      - name: Programa de Pós-Graduação em Sociologia (USP)