# Inspirado em: 
# - https://github.com/ipeadata-lab/curso_r_intro_202409/blob/main/_quarto.yml

project:
  type: book
  output-dir: docs
  resources: 
    - slides/
  
execute:
  freeze: auto

lang: pt 
language:
  title-block-author-single: "Autor"

book:
  title: "Análise de dados criminais usando linguagem R"
  site-url: "https://arturdamiao.github.io/2026-02-summer-intro-crime-analysis-R/"
  repo-url: "https://github.com/arturdamiao/2026-02-summer-intro-crime-analysis-R"
  navbar:
    logo: logo_en.png
    right: 
      - text: "Materiais"
        menu:
          - text: "Introdução à Programação para Humanidades"
            icon: youtube
            href: "https://youtube.com/playlist?list=PLInYN7O8R1DRcWN5pRvZfrG65RgtP1OB1&si=_Izok__wwjtfNpVH"
          - text: "Análise de dados criminais usando linguagem R"
            icon: youtube
            href: "https://www.youtube.com/playlist?list=PLInYN7O8R1DQnnLGNt6udOCpGoH3E7un1"
          - text: "[IPEA] Introdução à análise de dados no R"
            icon: pencil
            href: "https://ipeadata-lab.github.io/curso_r_intro_202409/"
      - text: "Slides"
        menu: 
          - text: "Slides Aula 01"
            icon: display
            href: slides/01-apresentacao.html
      - icon: youtube
        href: "https://www.youtube.com/playlist?list=PLInYN7O8R1DQnnLGNt6udOCpGoH3E7un1"

  chapters:
    - part: "Pré-curso"
      chapters:
        - index.qmd
        - chapters/instalacao.qmd
    - part: "Como analisar dados criminais?"
      chapters:
        - chapters/01-introducao.qmd
        - chapters/02-conhecendo-o-R.qmd
        - chapters/02a-manipulacao-dados.qmd
    - part: "O caso de São Paulo"
      chapters: 
        - chapters/03-importando-dados.qmd


page-navigation: true

page-footer: 
  border: true
  left: "Copyright 2026, Artur Damião" 
  right: 
    - icon: github
      href: https://github.com/arturdamiao/2026-02-summer-intro-crime-analysis-R



format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    toc-depth: 5
    link-external-icon: false
    link-external-newwindow: true
    reference-location: margin

bibliography: references.bib

editor: source
code-annotations: hover

author:
  - name: "Artur Damião"
    url: "https://www.arturdamiao.com/"
    email: "arturcardoso@usp.br"
    orcid: 0000-0002-8628-1653
    affiliation: 
      - name: Programa de Pós-Graduação em Sociologia (USP)